version: "3"
services:
#  mysql-prom:
#    image: prom/mysqld-exporter
#    environment:
#      - DATA_SOURCE_NAME=zipkin:zipkin@mysql
#    ports:
#      - "9104:9104"
#    deploy:
#      replicas: 1
#  mysql:
#    image: openzipkin/zipkin-mysql
#    ports:
#      - "3306:3306"
#    deploy:
#      replicas: 1

  # https://github.com/openzipkin/docker-zipkin/blob/master/docker-compose.yml
  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - "8890:9411"
#    environment:
#      - STORAGE_TYPE=mysql
#      - MYSQL_HOST=mysql
#    depends_on:
#      - mysql
    deploy:
      replicas: 1