version: "3"
services:
  sonarqube:
    image: sonarqube
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: v07IGCFCF83Z95NX
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
    ports:
      - "8888:9000"
      - "9092:9092"
    volumes:
      - /Users/cpu/dev/docker/sonarqube/sonarqube/conf:/opt/sonarqube/conf
      - /Users/cpu/dev/docker/sonarqube/sonarqube/data:/opt/sonarqube/data
      - /Users/cpu/dev/docker/sonarqube/sonarqube/extensions:/opt/sonarqube/extensions
      - /Users/cpu/dev/docker/sonarqube/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - db
    deploy:
      replicas: 1

  db:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    volumes:
      - /Users/cpu/dev/docker/sonarqube/postgresql/db:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - /Users/cpu/dev/docker/sonarqube/postgresql/data:/var/lib/postgresql/data
    deploy:
      replicas: 1


