version: "3"
services:
  ss:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8988:8388"
      - "8988:8388/udp"
    environment:
      - PASSWORD=${my_ss_password}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
