version: "3"
services:
  jenkins:
    image: jenkinsci/blueocean:1.9.0
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /root/ljy/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/gitClone:/home/gitClone
