#!/bin/sh

pids=`ps -ef | grep 1234 | grep ssh | grep -v grep|awk '{print $2}'`
if [ -z "$pids" ];then
	ssh -CqTfnN -D 1234 aws
fi

pids=`ps -ef | grep 1235 | grep ssh | grep -v grep|awk '{print $2}'`
if [ -z "$pids" ];then
	ssh -CqTfnN -D 1235 somanyad
fi
