version: "3"

services:
    test-admin:
        image: nginx
        container_name: app-admin
        ports:
            - 8000:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/usr/share/nginx/html
            - ./logs:/var/log/nginx